<?php


/**
 * Setup the theme functionalities, navigation menus, and custom thumbnail sizes
 */
function marble_setup() {
    //This will enable the title generated by WordPress
    add_theme_support('title-tag');

    //This will make our website support HTML 5 tags
    add_theme_support('html5', [
        'search-form',
		'comment-form',
		'comment-list',
		'gallery',
		'caption',
    ]);

    //Add support for feature thumbnaisls in post and pages
    add_theme_support('post-thumbnails');
    
    // add_image_size( 'custom-size', 200, 200, true );
    add_image_size( 'custom-size', 400, 200, true );

    add_image_size( 'project-custom-size', 380, 270, true );

    register_nav_menu('primary', 'The main navigation emplacement');
}

add_action( 'after_setup_theme', 'marble_setup' );

/**
 * register and add our script and styles to the loading process
 */
function marble_enqueue_scripts() {

    /*"<?= get_template_directory_uri();?>/css/styles.css"*/
    /*"<?= get_template_directory_uri();?>/css/normalize.css"*/

    wp_enqueue_style( 'marble', get_template_directory_uri() . '/css/styles.css' );
    wp_enqueue_style( 'normalize', get_template_directory_uri() . '/css/normalize.css' );
    wp_enqueue_style('googlefonts', 'https://fonts.googleapis.com/css?family=Roboto|Roboto+Condensed:400,700|Roboto+Slab:400,700');
    // wp_enqueue_script( 'script-name', get_template_directory_uri() . '/js/example.js', array('jquery' -- jquery depedency), '1.0.0' -- can be null, true -- like this gets loaded in the footer, if in the head then = false );

}

add_action('wp_enqueue_scripts', 'marble_enqueue_scripts');

/**
 * Register Theme sidebards
 */

 function marble_register_sidebars() {
    
    $args = [
        'name' => 'Footer sidebar',
        'id' => 'footer-sidebar',
        'description' => 'Widgets that are used in the footer area of my website.',
        'before_widget' => '<div id="%1$s" class="col widget %2$s">',
	    'after_widget'  => '</div>',
	    'before_title'  => '<h4 class="widgettitle">',
	    'after_title'   => '</h4>'
    ];
    
    register_sidebar($args);
 }

 add_action('widgets_init', 'marble_register_sidebars');

 /**
  * Register a custom post type to display the projects
  */

  // Register Custom Post Type
function marble_project_post_type() {

	$labels = array(
		'name'                  => _x( 'Projects', 'Post Type General Name', 'marble' ),
		'singular_name'         => _x( 'Project', 'Post Type Singular Name', 'marble' ),
		'menu_name'             => __( 'Projects', 'marble' ),
		'name_admin_bar'        => __( 'Project', 'marble' ),
		'archives'              => __( 'Item Archives', 'marble' ),
		'attributes'            => __( 'Item Attributes', 'marble' ),
		'parent_item_colon'     => __( 'Parent Item:', 'marble' ),
		'all_items'             => __( 'All Items', 'marble' ),
		'add_new_item'          => __( 'Add New Project', 'marble' ),
		'add_new'               => __( 'Add project', 'marble' ),
		'new_item'              => __( 'New project', 'marble' ),
		'edit_item'             => __( 'Edit project', 'marble' ),
		'update_item'           => __( 'Update project', 'marble' ),
		'view_item'             => __( 'View project', 'marble' ),
		'view_items'            => __( 'View project', 'marble' ),
		'search_items'          => __( 'Search project', 'marble' ),
		'not_found'             => __( 'Not found', 'marble' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'marble' ),
		'featured_image'        => __( 'Featured Image', 'marble' ),
		'set_featured_image'    => __( 'Set featured image', 'marble' ),
		'remove_featured_image' => __( 'Remove featured image', 'marble' ),
		'use_featured_image'    => __( 'Use as featured image', 'marble' ),
		'insert_into_item'      => __( 'Insert into item', 'marble' ),
		'uploaded_to_this_item' => __( 'Uploaded to this project', 'marble' ),
		'items_list'            => __( 'projects list', 'marble' ),
		'items_list_navigation' => __( 'projects list navigation', 'marble' ),
		'filter_items_list'     => __( 'Filter projects list', 'marble' ),
	);
	$args = array(
		'label'                 => __( 'Project', 'marble' ),
		'description'           => __( 'A project post type to display projects in your website', 'marble' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'editor', 'thumbnail', 'custom-fields' ),
		'taxonomies'            => array( 'type', ' color' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 20,
		'menu_icon'             => 'dashicons-format-gallery',
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'post',
		'show_in_rest'          => true,
		'rest_base'             => 'project',
	);
	register_post_type( 'project', $args );

}
add_action( 'init', 'marble_project_post_type', 0 );

/**
 * Register a custom taxonomy 'type' lined to the 'project' custom post
 * Custom taxonomies
 * Create some custom taxonomies with generatewp.com
 *
 */

// Register Custom Taxonomy
function marble_type_taxonomy() {

	$labels = array(
		'name'                       => _x( 'Types', 'Taxonomy General Name', 'marble' ),
		'singular_name'              => _x( 'Type', 'Taxonomy Singular Name', 'marble' ),
		'menu_name'                  => __( 'Type', 'marble' ),
		'all_items'                  => __( 'All Types', 'marble' ),
		'parent_item'                => __( 'Parent Type', 'marble' ),
		'parent_item_colon'          => __( 'Parent Type:', 'marble' ),
		'new_item_name'              => __( 'New Type Name', 'marble' ),
		'add_new_item'               => __( 'Add New Type', 'marble' ),
		'edit_item'                  => __( 'Edit Type', 'marble' ),
		'update_item'                => __( 'Update Type', 'marble' ),
		'view_item'                  => __( 'View Type', 'marble' ),
		'separate_items_with_commas' => __( 'Separate types with commas', 'marble' ),
		'add_or_remove_items'        => __( 'Add or remove types', 'marble' ),
		'choose_from_most_used'      => __( 'Choose from the most used', 'marble' ),
		'popular_items'              => __( 'Popular types', 'marble' ),
		'search_items'               => __( 'Search types', 'marble' ),
		'not_found'                  => __( 'Not Found', 'marble' ),
		'no_terms'                   => __( 'No types', 'marble' ),
		'items_list'                 => __( 'Types list', 'marble' ),
		'items_list_navigation'      => __( 'Types list navigation', 'marble' ),
	);
	$args = array(
		'labels'                     => $labels,
		'hierarchical'               => true,
		'public'                     => true,
		'show_ui'                    => true,
		'show_admin_column'          => true,
		'show_in_nav_menus'          => true,
		'show_tagcloud'              => true,
		'show_in_rest'               => true,
		'rest_base'                  => 'type',
	);
	register_taxonomy( 'type', array( 'project' ), $args );

}
add_action( 'init', 'marble_type_taxonomy', 0 );

/**
 * Register a custom 'color' taxonomy for the project post type
 */

 // Register Custom Taxonomy
function marble_color_taxonomy() {

	$labels = array(
		'name'                       => _x( 'Colors', 'Taxonomy General Name', 'marble' ),
		'singular_name'              => _x( 'Color', 'Taxonomy Singular Name', 'marble' ),
		'menu_name'                  => __( 'Color', 'marble' ),
		'all_items'                  => __( 'All Colors', 'marble' ),
		'parent_item'                => __( 'Parent Color', 'marble' ),
		'parent_item_colon'          => __( 'Parent Color:', 'marble' ),
		'new_item_name'              => __( 'New Color Name', 'marble' ),
		'add_new_item'               => __( 'Add New Color', 'marble' ),
		'edit_item'                  => __( 'Edit Color', 'marble' ),
		'update_item'                => __( 'Update Color', 'marble' ),
		'view_item'                  => __( 'View Color', 'marble' ),
		'separate_items_with_commas' => __( 'Separate colors with commas', 'marble' ),
		'add_or_remove_items'        => __( 'Add or remove colors', 'marble' ),
		'choose_from_most_used'      => __( 'Choose from the most used', 'marble' ),
		'popular_items'              => __( 'Popular colors', 'marble' ),
		'search_items'               => __( 'Search colors', 'marble' ),
		'not_found'                  => __( 'Not Found', 'marble' ),
		'no_terms'                   => __( 'No colors', 'marble' ),
		'items_list'                 => __( 'Colors list', 'marble' ),
		'items_list_navigation'      => __( 'Colors list navigation', 'marble' ),
	);
	$args = array(
		'labels'                     => $labels,
		'hierarchical'               => false,
		'public'                     => true,
		'show_ui'                    => true,
		'show_admin_column'          => true,
		'show_in_nav_menus'          => true,
		'show_tagcloud'              => true,
		'show_in_rest'               => true,
		'rest_base'                  => 'color',
	);
	register_taxonomy( 'color', array( 'project' ), $args );

}
add_action( 'init', 'marble_color_taxonomy', 0 );

// Register Custom Post Type
function marble_feature_post_type() {

	$labels = array(
		'name'                  => _x( 'Features', 'Post Type General Name', 'text_domain' ),
		'singular_name'         => _x( 'Feature', 'Post Type Singular Name', 'text_domain' ),
		'menu_name'             => __( 'Features', 'text_domain' ),
		'name_admin_bar'        => __( 'Feature', 'text_domain' ),
		'archives'              => __( 'Feature Archives', 'text_domain' ),
		'attributes'            => __( 'Feature Attributes', 'text_domain' ),
		'parent_item_colon'     => __( 'Parent Feature:', 'text_domain' ),
		'all_items'             => __( 'All Features', 'text_domain' ),
		'add_new_item'          => __( 'Add New Feature', 'text_domain' ),
		'add_new'               => __( 'Add New feature', 'text_domain' ),
		'new_item'              => __( 'New Feature', 'text_domain' ),
		'edit_item'             => __( 'Edit Feature', 'text_domain' ),
		'update_item'           => __( 'Update Feature', 'text_domain' ),
		'view_item'             => __( 'View Feature', 'text_domain' ),
		'view_items'            => __( 'View Features', 'text_domain' ),
		'search_items'          => __( 'Search Feature', 'text_domain' ),
		'not_found'             => __( 'Not found', 'text_domain' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'text_domain' ),
		'featured_image'        => __( 'Featured Image', 'text_domain' ),
		'set_featured_image'    => __( 'Set featured image', 'text_domain' ),
		'remove_featured_image' => __( 'Remove featured image', 'text_domain' ),
		'use_featured_image'    => __( 'Use as featured image', 'text_domain' ),
		'insert_into_item'      => __( 'Insert into feature', 'text_domain' ),
		'uploaded_to_this_item' => __( 'Uploaded to this feature', 'text_domain' ),
		'items_list'            => __( 'Features list', 'text_domain' ),
		'items_list_navigation' => __( 'Features list navigation', 'text_domain' ),
		'filter_items_list'     => __( 'Filter feature list', 'text_domain' ),
	);
	$args = array(
		'label'                 => __( 'Feature', 'text_domain' ),
		'description'           => __( 'feature to be displayed in the front-page', 'text_domain' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'editor', 'custom-fields' ),
		'hierarchical'          => true,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => false,
		'exclude_from_search'   => true,
		'publicly_queryable'    => true,
		'rewrite'               => false,
		'capability_type'       => 'page',
		'show_in_rest'          => false,
	);
	register_post_type( 'feature', $args );

}
add_action( 'init', 'marble_feature_post_type', 0 );

require get_template_directory() . '/inc/Wf3_Widget.php';


